
spring:
  profiles:
    active: dev

  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

jwt:
  secret: "my-super-secure-jwt-secret-key-2024!!"
server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG




