
spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mariadb://mariadb:30306/aiarc
    username: root
    password: elwlzoq100$
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: "my-super-secure-jwt-secret-key-2024!!"
server:
  port: 8081
