apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command: [ 'sh', '-c', 'until nc -z mariadb 3306; do echo waiting for mariadb; sleep 2; done;' ]
        - name: wait-for-redis
          image: busybox
          command: [ 'sh', '-c', 'until nc -z redis-service 6379; do echo waiting for redis; sleep 2; done;' ]
      containers:
        - name: auth-service
          image: 10.1.223.21:5000/auth-service:__TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: auth-storage
              mountPath: /data/auth
      volumes:
        - name: auth-storage
          persistentVolumeClaim:
            claimName: auth-pvc
