apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command: [ 'sh', '-c', 'until nc -z mariadb 3306; do echo waiting for mariadb; sleep 2; done;' ]
        - name: wait-for-redis
          image: bitnami/redis:7.2.4
          command: [ 'sh', '-c', 'until redis-cli -h redis-service -p 6379 ping | grep PONG; do echo waiting for redis; sleep 2; done' ]
      containers:
        - name: auth-service
          image: 10.1.223.21:5000/auth-service:__TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: auth-storage
              mountPath: /data/auth
          # 🔧 디버그 도구용 sidecar
#        - name: debug
#          image: nicolaka/netshoot
#          command: [ "sleep", "infinity" ]
#          stdin: true
#          tty: true
      volumes:
        - name: auth-storage
          persistentVolumeClaim:
            claimName: auth-pvc
