apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
  labels:
    app: auth
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.1.223.19
    path: /srv/nfs/auth-data  # NFS에서 공유된 디렉토리
